# [dbo].[Provincia]

In [0]:
USE [DB_OPCOIN]
GO

In [0]:
SET IDENTITY_INSERT [dbo].[Provincia] ON 
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (1, N'Buenos Aires')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (2, N'Catamarca')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (3, N'Chaco')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (4, N'Chubut')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (5, N'Córdoba')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (6, N'Corrientes')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (7, N'Entre Ríos')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (8, N'Formosa')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (9, N'Jujuy')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (10, N'La Pampa')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (11, N'La Rioja')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (12, N'Mendoza')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (13, N'Misiones')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (14, N'Neuquén')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (15, N'Río Negro')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (16, N'Salta')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (17, N'San Juan')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (18, N'San Luis')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (19, N'Santa Cruz')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (20, N'Santa Fe')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (21, N'Santiago del Estero')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (22, N'Tierra del Fuego')
INSERT [dbo].[Provincia] ([ID_Provincia], [NombreProvincia]) VALUES (23, N'Tucumán')
SET IDENTITY_INSERT [dbo].[Provincia] OFF
GO

# [dbo].[Localidad]

In [0]:
SET IDENTITY_INSERT [dbo].[Localidad] ON 
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (1, N'Adolfo Gonzalez Chaves', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (2, N'Aguas Verdes', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (3, N'Alberti', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (4, N'Arenas Verdes', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (5, N'Arrecifes', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (6, N'Ayacucho', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (7, N'Azul', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (8, N'Bahia Blanca', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (9, N'Bahia San Blas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (10, N'Balcarce', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (11, N'BalnearioSan Cayetano', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (12, N'Baradero', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (13, N'Benito Juarez', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (14, N'Berisso', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (15, N'Bolivar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (16, N'Bragado', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (17, N'Brandsen', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (18, N'Campana', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (19, N'Cañuelas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (20, N'Capilla del Señor', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (21, N'Capitan Sarmiento', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (22, N'Carhue', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (23, N'Carilo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (24, N'Carlos Casares', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (25, N'Carlos Keen ', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (26, N'Carlos Tejedor', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (27, N'Carmen de Areco', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (28, N'Carmen de Patagones', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (29, N'Castelli', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (30, N'Chacabuco', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (31, N'Chapadmalal', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (32, N'Chascomus', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (33, N'Chivilcoy', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (34, N'Ciudad de Bs As', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (35, N'Claromeco', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (36, N'Colon', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (37, N'Coronel Olmedo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (38, N'Caronel Pringles', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (39, N'Coronel Suarez', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (40, N'Coronel Vidal', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (41, N'Costa Azul', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (42, N'Costa Chica', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (43, N'Costa Este', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (44, N'Costa Esmeralda', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (45, N'Daireaux', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (46, N'Dolores', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (47, N'Ensenada', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (48, N'Escobar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (49, N'Exaltación de la Cruz', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (50, N'Ezeiza', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (51, N'Florentino Ameghino', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (52, N'General Belgrano', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (53, N'General Lamadrid', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (54, N'General LasHeras', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (55, N'General Lavalle', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (56, N'General Madariaga', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (57, N'General Pinto', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (58, N'General Rodriguez', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (59, N'General Villegas ', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (60, N'Guaminí', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (61, N'Huanguelen', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (62, N'Junin', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (63, N'La Lucila de Mar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (64, N'LA Plata', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (65, N'LAs Gaviotas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (66, N'Las Flores', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (67, N'Las Toninas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (68, N'Lincoln', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (70, N'Lobería', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (71, N'Lobos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (72, N'Los Toldos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (73, N'Lujan', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (74, N'Magdalena', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (75, N'Maipu', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (76, N'Mar Azul', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (77, N'Mar Chuiquita', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (78, N'Mar de Ajo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (79, N'Mar de Cobo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (80, N'Mar de las Pampas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (81, N'Mar del Plata', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (82, N'Mar del Sur', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (83, N'Mar del Tuyu', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (84, N'Marisol', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (85, N'Medanos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (86, N'Mercedes', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (87, N'Miramar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (88, N'Monte Hermoso', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (89, N'Navarro', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (90, N'Necochea', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (91, N'Nueva Atlantis', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (92, N'Nueve de Julio', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (93, N'Olavarria', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (94, N'Orense', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (95, N'Oriente', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (96, N'Ostende', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (97, N'Pedro Luro', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (98, N'Pehuajo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (99, N'Pehuen Co', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (100, N'Pergamino', 1)
GO

In [0]:
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (101, N'Pigüé', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (102, N'Pilar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (103, N'Pinamar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (104, N'Pinar del Sol', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (105, N'Pipinas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (106, N'Puan', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (107, N'Punta Alta', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (108, N'Punta Indio', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (109, N'Punta Medanos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (110, N'Quequen', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (111, N'Quilmes', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (112, N'Ramallo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (113, N'Ranchos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (114, N'Rauch', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (115, N'Reta', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (116, N'Rivadavia Bs As', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (117, N'Rojas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (118, N'Roque Perez', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (119, N'Saavedra', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (120, N'Saladillo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (121, N'Saldungaray', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (122, N'Salto', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (123, N'San Andres de Giles', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (124, N'San Antonio de Areco', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (125, N'San Bernardo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (126, N'San Cayetano', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (127, N'San Clemente del Tuyu', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (128, N'San Fernando', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (129, N'San Isidro', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (130, N'San Miguel del Monte', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (131, N'San Nicolas ', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (132, N'San Pedro ', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (133, N'Santa Clara del Mar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (134, N'Santa Teresita', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (135, N'Sierras Bayas', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (136, N'Sierra de la Ventana', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (137, N'Sierra de los Padres', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (138, N'Suipacha', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (139, N'Tandil', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (140, N'Tapalque', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (141, N'Tigre', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (142, N'Tornquist', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (143, N'Tomas Jofre', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (144, N'Treinta de Agosto', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (145, N'Trenque Launquen', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (146, N'Tres Arroyos', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (147, N'Valeria del Mar', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (148, N'Vedia', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (149, N'Veinticinco de Mayo', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (150, N'Verónica', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (151, N'Vicente Caseres', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (152, N'Villa Gesell', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (153, N'Villalonga', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (154, N'Villa la Arcadia', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (155, N'Villa Serrana la Gruta', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (156, N'Villa Ventana', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (157, N'Zarate', 1)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (158, N'Aconquija', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (159, N'Alijilan', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (160, N'Ancasti', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (161, N'Andalgala', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (162, N'Antofagasta', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (163, N'Belen', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (165, N'El Alto', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (166, N'El Rodeo', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (167, N'Fiambala', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (169, N'Icaño', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (170, N'La Paz', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (171, N'La Puerta', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (172, N'Las Juntas', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (173, N'Los Altos', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (174, N'Paclin', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (175, N'Poman', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (176, N'Recreo', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (177, N'San Ferandno del Valle', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (178, N'San Isidro', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (179, N'Sangta María', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (180, N'Saujil', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (181, N'Sumampa', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (182, N'Tinogasta', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (183, N'Villa las Pirquitas', 2)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (184, N'Avia Terai', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (185, N'Charata', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (186, N'El suzalito', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (187, N'Fuerte esperanza', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (188, N'Gancedo', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (189, N'General Pinedo', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (190, N'General San Martín', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (191, N'General Vedia', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (192, N'Hermoso Campo', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (193, N'Isla de Cerrito', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (194, N'Jan Jose Castelli', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (195, N'Las Breñas', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (196, N'Marchagai', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (197, N'Mision Nueva Pompeya', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (198, N'Pampa del Indio', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (199, N'Puerto Tirol', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (200, N'Residencia', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (201, N'Roque Saenz Peña', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (202, N'Villa Angela ', 3)
GO

In [0]:
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (203, N'Villa Río Bermejito', 3)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (204, N'Alto Río Senguer', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (205, N'Bahía Bustamante', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (206, N'Camarones', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (207, N'Cholila', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (208, N'Comodoro Rivadavia', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (209, N'Corcovado', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (210, N'E Hoyo', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (211, N'El Maiten', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (212, N'Epuyen', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (213, N'Esquel', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (214, N'Gaiman', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (215, N'Gobernador Costa', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (216, N'Jose de San Martín', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (217, N'Lago Ouelo', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (218, N'Playa Unión', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (219, N'Puerto Madryn', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (220, N'Puerto Piramides', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (221, N'Rawson', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (222, N'Rada Tilly', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (223, N'Río Mayo', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (224, N'Río Pico', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (225, N'Sarmiento ', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (226, N'Trelew', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (227, N'Trevelin', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (228, N'Villa Ameghino', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (229, N'Villa Futalaufquen', 4)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (230, N'Achiras', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (231, N'Agua de Oro', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (232, N'Alcira Gigena', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (233, N'Almafuerte', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (234, N'Alpa Corral', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (235, N'Alta Gracia', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (237, N'Amboy', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (238, N'Anisacate', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (239, N'Arroyito', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (240, N'Arroyo de los Patos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (241, N'Ascochinga', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (242, N'Athos Pampa', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (243, N'Balnearia', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (244, N'Bell Ville', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (245, N'Bialet Masse', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (246, N'Cabalango', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (247, N'Calmayo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (248, N'Capilla del Monte ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (249, N'Casa Grande', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (250, N'Cerro Colorado', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (251, N'Charboinier', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (252, N'Colonia Caroya', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (253, N'Copacabana', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (254, N'Córdoba', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (255, N'Cosquin', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (256, N'Cruz Alta', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (257, N'Cruz Chica', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (258, N'Cruz del Eje', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (259, N'Cruz Grande', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (260, N'Cuesta Blanca ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (261, N'Dean Funes', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (262, N'Del Campillo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (263, N'Despeñaderos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (264, N'El Durazno', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (265, N'Embalse', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (266, N'General Deheza', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (267, N'General Levalle', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (268, N'Hernando', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (269, N'Huerta Grande ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (270, N'Huinca Renanco', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (271, N'Icho Cruz', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (272, N'Intiyaco', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (273, N'Ischilin', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (274, N'James Craik', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (275, N'Jesus María', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (276, N'La Bolsa ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (277, N'Laboulaye', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (278, N'La Calera', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (279, N'La Carlota', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (280, N'La Cesira', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (281, N'La Cruz', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (282, N'La Cumbre', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (283, N'La Cumbrecita', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (284, N'La Falda', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (285, N'La Granja', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (286, N'La Paisanita', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (287, N'La Paz Córdoba', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (288, N'La Población', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (289, N'Las Albacas', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (290, N'Las Caleras', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (291, N'Las Calles', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (292, N'La serranita', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (293, N'Las Rabonas', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (294, N'Las Tapias', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (295, N'Loma Bola', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (296, N'Los Cocos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (297, N'Los Condores', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (298, N'Los Hornillos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (299, N'Los Molinos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (300, N'Los Pozos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (301, N'Los Reartes', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (302, N'Loza Corral', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (303, N'Marcos Juarez', 5)
GO

In [0]:
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (304, N'Mayu Sumaj', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (305, N'Mendiolaza', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (306, N'Mina Clavero', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (307, N'Miramar', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (308, N'Molinari', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (309, N'Minte Maiz', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (310, N'Morteros', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (311, N'Nono', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (312, N'Oncativo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (314, N'Ongamira', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (315, N'Panahola', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (316, N'Potrero de Garay', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (317, N'Quilino', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (318, N'Río Ceballo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (319, N'Río de los Sauces', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (320, N'Río Tercero', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (321, N'Saldan', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (322, N'Salsacate ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (323, N'Salsipuedes', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (324, N'San Antonio de Arredondo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (325, N'San CarlosMina', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (326, N'San Clemente', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (327, N'San esteban', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (328, N'San Francisco', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (329, N'San Javier de Traslasierras', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (330, N'San Jose de la Dormida', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (331, N'San Marcos Sierras', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (332, N'San Roque', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (333, N'Santa Cruz del Lago', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (334, N'Santa María de Punilla', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (335, N'Santa Monica', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (336, N'Santa Rosa de Calamuchita', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (337, N'Sinsacate', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (338, N'Tala Huasi', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (339, N'Tancacha', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (340, N'Tanti', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (341, N'Unquillo', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (342, N'Valle Hermoso', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (343, N'Villa Alpina', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (344, N'Villa Allende ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (345, N'Villa Animi', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (346, N'Villa Ascasubi', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (347, N'Villa Berna', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (348, N'Villa Carlos Paz', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (349, N'Villa Ciudad America', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (350, N'Villa Ciudad Parque', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (351, N'Villa Cura Brochero', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (352, N'Villa de las Rosas', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (353, N'Villa del Dique', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (354, N'Villa del Soto', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (355, N'Villa del Totoral', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (356, N'Villa de María', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (357, N'Villa Dolores', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (358, N'Villa General Belgrano ', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (359, N'Villa Giardino', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (360, N'Villa Los Aromos', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (361, N'Villa María', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (363, N'Villa Parque Siquiman', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (364, N'Villa Rumipal', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (365, N'Villa Tulumba', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (366, N'Yacanto Calamuchita', 5)
INSERT [dbo].[Localidad] ([ID_Localidad], [NombreLocalidad], [ID_Provincia]) VALUES (367, N'Yacanto Traslasierra', 5)
SET IDENTITY_INSERT [dbo].[Localidad] OFF
GO

# [dbo].[Rol]

In [0]:
SET IDENTITY_INSERT [dbo].[Rol] ON 
INSERT [dbo].[Rol] ([ID_Rol], [NombreRol], [Descripcion]) VALUES (1, N'admin', N'adminstrador de plataforma')
INSERT [dbo].[Rol] ([ID_Rol], [NombreRol], [Descripcion]) VALUES (2, N'user', N'usuario de plataforma')
INSERT [dbo].[Rol] ([ID_Rol], [NombreRol], [Descripcion]) VALUES (3, N'guest', N'usuario invitado')
SET IDENTITY_INSERT [dbo].[Rol] OFF
GO

# [dbo].[TipoDocumento]

In [0]:
SET IDENTITY_INSERT [dbo].[TipoDocumento] ON 
INSERT [dbo].[TipoDocumento] ([ID_TipoDocumento], [NombreTipoDocumento], [Descripcion]) VALUES (1, N'L.C.', N'Libreta Cívica')
INSERT [dbo].[TipoDocumento] ([ID_TipoDocumento], [NombreTipoDocumento], [Descripcion]) VALUES (2, N'L.E.', N'Libreta de Enrolamiento')
INSERT [dbo].[TipoDocumento] ([ID_TipoDocumento], [NombreTipoDocumento], [Descripcion]) VALUES (3, N'D.N.I.', N'Documento Nacional de Identidad')
SET IDENTITY_INSERT [dbo].[TipoDocumento] OFF
GO

# [dbo].[TipoMoneda]

In [0]:
SET IDENTITY_INSERT [dbo].[TipoMoneda] ON 
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (1, N'BTC', N'Bitcoin')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (2, N'ETH', N'Ethereum')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (3, N'USDT', N'Tether')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (4, N'USDC', N'USD Coin')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (5, N'BNB', N'Binance Coin')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (6, N'BUSD', N'Binance USD')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (7, N'XRP', N'Ripple')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (8, N'ADA', N'Cardano')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (9, N'SOL', N'Solana')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (10, N'DOGE', N'Dogecoin')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (11, N'DOT', N'Polkadot')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (12, N'MATIC', N'Polygom')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (13, N'DAI', N'DAI')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (14, N'SHIB', N'Shiba Inu')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (15, N'TXR', N'Tron')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (16, N'AVAX', N'Avalanche')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (17, N'LTC', N'Litecoin')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (18, N'BITBAY', N'BitBay')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (19, N'XLM', N'Stellar XLM')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (20, N'BCH', N'Bitcoin Cash BCH')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (21, N'LINK', N'Chainlink')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (22, N'IOTA MIOTA', N'IOTA MIOTA')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (23, N'XMR', N'Monero')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (24, N'NEO', N'NEO')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (25, N'XTZ', N'Tezos')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (26, N'THETA', N'Theta')
INSERT [dbo].[TipoMoneda] ([ID_TipoMoneda], [NombreTipoMoneda], [Descripcion]) VALUES (27, N'UNI', N'Uniswap ')
SET IDENTITY_INSERT [dbo].[TipoMoneda] OFF
GO